name: test

channels:
  - https://conda.anaconda.org/conda-forge

dependencies:
  - anaconda-project =0.9.1
  - conda =4.12
  - doit ==0.32
  - mamba =0.22.1
  - pip
  - python >=3.8,<3.9
  - twine
  - wheel
