name: ipyelk

channels:
  - https://conda.anaconda.org/conda-forge

dependencies:
  - async-lru >=1,<2
  - importnb
  - ipython >=7
  - ipywidgets >=7.5.1
  - jupyterlab >=1.2,<1.3.0a0
  - networkx
  - nodejs >=14,<15
  - pandas
  - python >=3.7
