name: ipyelk

channels:
  - anaconda
  - conda-forge
  - msys2

dependencies:
  - ipywidgets >=7.5.1
  - jupyterlab >=1.2,<1.3.0a0
  - networkx
  - nodejs >=10,<14.0.0a0
  - pandas
  - python >=3.7
  - ipython >=7
