name: ipyelk

channels:
  - https://conda.anaconda.org/conda-forge
  - https://conda.anaconda.org/anaconda
  - https://conda.anaconda.org/msys2

dependencies:
  - ipywidgets >=7.5.1
  - jupyterlab >=1.2,<1.3.0a0
  - networkx
  - nodejs >=14,<15
  - pandas
  - python >=3.7
  - ipython >=7
  # TODO: remove when available from conda-forge
  - pip
  - pip:
      - async_lru >=1,<2
