name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  PYTHONUNBUFFERED: 1

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    steps:
      - uses: actions/checkout@v2

      - uses: goanpeca/setup-miniconda@v1.6.0
        with:
          activate-environment: ipyelk
          auto-activate-base: false
          environment-file: environment.yml
          show-channel-urls: true
          use-only-tar-bz2: true

      - if: ${{ !contains(matrix.os, 'windows') }}
        shell: bash -l {0}
        run: |
          anaconda-project run setup
          anaconda-project run lint

      - if: ${{ contains(matrix.os, 'windows') }}
        shell: cmd /C CALL {0}
        run: |
          anaconda-project run setup
          anaconda-project run lint

